### ISSUE TITLE
First "brew doctor" does not yield any errors. Only after updating git (next step)

### ISSUE THREAD

**Issue by hqcasanova** [mayanring/rails-dev-setup-guide#2]
Just a minor correction but one that could help avoid some confusion. First time "brew doctor" is executed, there are no warnings regarding git (as shown in the image included in the text). It's not until the next step that there are two versions of git installed: the system's and the one just installed using "brew install". Perhaps the chunk of text dealing with "brew doctor" and paths should be moved into the "Git section"?

**Comment by mayanring** [comment]
So that screenshot was taken almost a year ago when I helped someone setup their dev environment. It's entirely possible that you won't have the same error when you run "brew doctor" (I'm sure they change the install script all the time).

This step has nothing to do with git, despite the screenshot. The point is to show that the PATH needs to have /usr/local/bin near the beginning, in front of the default system paths.
